version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

executors:
  clojure:
    docker:
      - image: circleci/clojure:tools-deps-1.10.0.442
    working_directory: ~/propel

commands:
  with-deps:
    parameters:
      cache-key:
        description: "Checksums to differentiate the job's cache."
        type: string
        default: "default"
      steps:
        description: "Steps to execute after the repo and deps are fetched but before the cache is saved."
        type: steps
        default: []
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-<< parameters.cache-key >>
      - steps: << parameters.steps >>
      - save_cache:
          paths:
            - ~/.m2
          key: deps-<< parameters.cache-key >>

jobs:
  test:
    executor: clojure
    steps:
      - with-deps:
          cache-key: test-{{ checksum "deps.edn" }}
          steps:
            - run: >
                bin/kaocha
                --plugin kaocha.plugin/junit-xml
                --junit-xml-file test-results/kaocha/results.xml
                --plugin cloverage --no-cov-html --codecov
            - store_test_results:
                path: test-results
            - codecov/upload:
                file: target/coverage/codecov.json

workflows:
  version: 2
  checks:
    jobs:
      - test
